## 列表

In [1]:
x = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
print(x, type(x))
# ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'] <class 'list'>

x = [2, 3, 4, 5, 6, 7]
print(x, type(x))
# [2, 3, 4, 5, 6, 7] <class 'list'>

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'] <class 'list'>
[2, 3, 4, 5, 6, 7] <class 'list'>


##### 利用range()创建列表

In [3]:
x = list(range(10))
print(x, type(x))
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>

x = list(range(1, 11, 2))
print(x, type(x))
# [1, 3, 5, 7, 9] <class 'list'>

x = list(range(10, 1, -2))
print(x, type(x))
# [10, 8, 6, 4, 2] <class 'list'>

x = [0] * 5
print(x, type(x))
# [0, 0, 0, 0, 0] <class 'list'>

x = [0 for i in range(5)]
print(x, type(x))
# [0, 0, 0, 0, 0] <class 'list'>

x = [i for i in range(10)]
print(x, type(x))
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>

x = [i for i in range(1, 10, 2)]
print(x, type(x))
# [1, 3, 5, 7, 9] <class 'list'>

x = [i for i in range(10, 1, -2)]
print(x, type(x))
# [10, 8, 6, 4, 2] <class 'list'>

x = [i ** 2 for i in range(1, 10)]
print(x, type(x))
# [1, 4, 9, 16, 25, 36, 49, 64, 81] <class 'list'>

x = [i for i in range(100) if (i % 2) != 0 and (i % 3) == 0]
print(x, type(x))

# [3, 9, 15, 21, 27, 33, 39,

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>
[1, 3, 5, 7, 9] <class 'list'>
[10, 8, 6, 4, 2] <class 'list'>
[0, 0, 0, 0, 0] <class 'list'>
[0, 0, 0, 0, 0] <class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>
[1, 3, 5, 7, 9] <class 'list'>
[10, 8, 6, 4, 2] <class 'list'>
[1, 4, 9, 16, 25, 36, 49, 64, 81] <class 'list'>
[3, 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99] <class 'list'>


注意：

由于list的元素可以是任何对象，因此列表中所保存的是对象的指针。即使保存一个简单的[1,2,3]，也有3个指针和3个整数对象。

x = [a] * 4操作中，只是创建4个指向list的引用，所以一旦a改变，x中4个a也会随之改变。

In [5]:
a = 1
x = [a] * 4
print(x)

a = 2
print(x)

x = [[0] * 3] * 4
print(x, type(x))
# [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]] <class 'list'>

x[0][0] = 1
print(x, type(x))
# [[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]] <class 'list'>

a = [0] * 3
x = [a] * 4
print(x, type(x))
# [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]] <class 'list'>

x[0][0] = 1
print(x, type(x))
# [[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]] <class 'list'>

[1, 1, 1, 1]
[1, 1, 1, 1]
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]] <class 'list'>
[[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]] <class 'list'>
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]] <class 'list'>
[[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]] <class 'list'>


### 注意用[n]*x 的方法创建的列表

## 列表的常见操作

##### 添加元素

In [8]:
x = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
x.append('Thursday')
print(x) 

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Thursday']


##### append ; extend ; insert

list.append(obj) 在列表末尾添加新的对象，只接受一个参数，参数可以是任何数据类型，被追加的元素在 list 中保持着原结构类型。

In [10]:
x = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
x.append(['Thursday', 'Sunday'])
print(x)  
# ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', ['Thursday', 'Sunday']]

print(len(x))  # 6

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', ['Thursday', 'Sunday']]
6


list.extend(seq) 在列表末尾一次性追加另一个序列中的多个值（用新列表扩展原来的列表）

In [11]:
x = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
x.extend(['Thursday', 'Sunday'])
print(x)  
# ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Thursday', 'Sunday']

print(len(x))  # 7

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Thursday', 'Sunday']
7


list.insert(index, obj) 在编号 index 位置插入 obj。

In [12]:
x = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
x.insert(2, 'Sunday')
print(x)
# ['Monday', 'Tuesday', 'Sunday', 'Wednesday', 'Thursday', 'Friday']

print(len(x))  # 6

['Monday', 'Tuesday', 'Sunday', 'Wednesday', 'Thursday', 'Friday']
6


##### 删除元素
##### remove;pop;del

list.remove(obj) 移除列表中某个值的第一个匹配项

In [13]:
x = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
x.remove('Monday')
print(x)  # ['Tuesday', 'Wednesday', 'Thursday', 'Friday']

['Tuesday', 'Wednesday', 'Thursday', 'Friday']


list.pop([index=-1]) 移除列表中的一个元素（默认最后一个元素），并且返回该元素的值

In [14]:
x = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
y = x.pop()
print(y)  # Friday

y = x.pop(0)
print(y)  # Monday

y = x.pop(-2)
print(y)  # Wednesday
print(x)  # ['Tuesday', 'Thursday']

Friday
Monday
Wednesday
['Tuesday', 'Thursday']


del var1[, var2 ……] 删除单个或多个对象。

如果知道要删除的元素在列表中的位置，可使用del语句。

In [15]:
x = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
del x[0:2]
print(x)  # ['Wednesday', 'Thursday', 'Friday']

['Wednesday', 'Thursday', 'Friday']


##### 切片
 切片的通用写法是 start : stop : step

In [16]:
x = ['Monday', 'Tuesday', 'Wednesday', ['Thursday', 'Friday']]
print(x[0], type(x[0]))  # Monday <class 'str'>
print(x[-1], type(x[-1]))  # ['Thursday', 'Friday'] <class 'list'>
print(x[-2], type(x[-2]))  # Wednesday <class 'str'>

Monday <class 'str'>
['Thursday', 'Friday'] <class 'list'>
Wednesday <class 'str'>


In [21]:
print(x[3:])  # ['Thursday', 'Friday']
print(x[-3:])  # ['Wednesday', 'Thursday', 'Friday']

['Thursday', 'Friday']
['Wednesday', 'Thursday', 'Friday']


In [18]:
week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
print(week[:3])  # ['Monday', 'Tuesday', 'Wednesday']
print(week[:-3])  # ['Monday', 'Tuesday']

['Monday', 'Tuesday', 'Wednesday']
['Monday', 'Tuesday']


In [20]:
print(week[1:3])  # ['Tuesday', 'Wednesday']
print(week[-3:-1])  # ['Wednesday', 'Thursday']

['Tuesday', 'Wednesday']
['Wednesday', 'Thursday']


以具体的 step 从编号 start 往编号 stop 切片。注意最后把 step 设为 -1，相当于将列表反向排列。

In [22]:
week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
print(week[1:4:2])  # ['Tuesday', 'Thursday']
print(week[:4:2])  # ['Monday', 'Wednesday']
print(week[1::2])  # ['Tuesday', 'Thursday']
print(week[::-1])  
# ['Friday', 'Thursday', 'Wednesday', 'Tuesday', 'Monday']

['Tuesday', 'Thursday']
['Monday', 'Wednesday']
['Tuesday', 'Thursday']
['Friday', 'Thursday', 'Wednesday', 'Tuesday', 'Monday']


复制列表中的所有元素（浅拷贝）。

In [23]:
week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
print(week[:])  
# ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']


浅拷贝：创建一个新的对象，但新对象的内部元素仍然是对原对象内部元素的引用。也就是说，浅拷贝只复制了对象的一层结构，如果原对象的元素是可变对象，修改原对象的这些可变元素会影响到浅拷贝的对象。

深拷贝：创建一个新的对象，并且递归地复制原对象的所有元素，包括嵌套的对象。深拷贝会完全独立于原对象，修改原对象不会影响到深拷贝的对象。

In [24]:
list1 = [123, 456, 789, 213]

list2 = list1
"""这行代码并不是拷贝操作，而是让 list2 指向了和 list1 相同的内存地址，
即 list2 和 list1 实际上是同一个列表对象的两个不同引用。
所以，当对 list1 进行排序操作(list1.sort())时,list2 也会受到影响，因为它们指向同一个列表。"""

list3 = list1[:]
"""这是一种浅拷贝操作。list1[:] 会创建一个新的列表对象 list3,
并将 list1 中的元素复制到 list3 中。由于这里的元素是不可变对象（整数），
所以 list3 中的元素和 list1 中的元素虽然值相同，但它们在内存中是独立的。
因此，当对 list1 进行排序操作时,list3 不会受到影响。"""
print(list2)  # [123, 456, 789, 213]   
print(list3)  # [123, 456, 789, 213]    
list1.sort()
print(list2)  # [123, 213, 456, 789]   随list1变化
print(list3)  # [123, 456, 789, 213]   不随list1变化

[123, 456, 789, 213]
[123, 456, 789, 213]
[123, 213, 456, 789]
[123, 456, 789, 213]


In [25]:
list1 = [[123, 456], [789, 213]]
list2 = list1
"""同样，这只是让 list2 和 list1 指向同一个列表对象，所以它们会同步变化。
"""
list3 = list1[:]
"""这是浅拷贝操作。list3 是一个新的列表对象，但是它内部的元素（子列表）仍然是对 list1 中对应子列表的引用。
也就是说,list3 和 list1 中的子列表指向相同的内存地址。当修改 list1[0][0] 时，
实际上是修改了 list1 中第一个子列表的第一个元素，由于 list3 中的第一个子列表和 list1 中的第一个子列表是同一个对象，
所以 list3 也会受到影响。"""
print(list2)  # [[123, 456], [789, 213]]
print(list3)  # [[123, 456], [789, 213]]
list1[0][0] = 111
print(list2)  # [[111, 456], [789, 213]]
print(list3)  # [[111, 456], [789, 213]]

[[123, 456], [789, 213]]
[[123, 456], [789, 213]]
[[111, 456], [789, 213]]
[[111, 456], [789, 213]]


如果要实现完全独立的拷贝，可以使用 copy 模块中的 deepcopy 函数。以下是一个示例：

在这个示例中，list2 是 list1 的深拷贝，它和 list1 完全独立，修改 list1 不会影响到 list2。

In [26]:
import copy

list1 = [[123, 456], [789, 213]]
list2 = copy.deepcopy(list1)
list1[0][0] = 111
print(list1)  # [[111, 456], [789, 213]]
print(list2)  # [[123, 456], [789, 213]]

[[111, 456], [789, 213]]
[[123, 456], [789, 213]]


### 列表的常用操作符

等号操作符：==\

连接操作符 +

重复操作符 *

成员关系操作符 in、not in

「等号 ==」，只有成员、成员位置都相同时才返回True。

列表拼接有两种方式，用「加号 +」和「乘号 *」，前者首尾拼接，后者复制拼接。

In [27]:
list1 = [123, 456]
list2 = [456, 123]
list3 = [123, 456]

print(list1 == list2)  # False
print(list1 == list3)  # True

list4 = list1 + list2  # extend()
print(list4)  # [123, 456, 456, 123]

list5 = list3 * 3
print(list5)  # [123, 456, 123, 456, 123, 456]

list3 *= 3
print(list3)  # [123, 456, 123, 456, 123, 456]

print(123 in list3)  # True
print(456 not in list3)  # False

False
True
[123, 456, 456, 123]
[123, 456, 123, 456, 123, 456]
[123, 456, 123, 456, 123, 456]
True
False


### 列表的其它方法

list.count(obj) 统计某个元素在列表中出现的次数

In [28]:
list1 = [123, 456] * 3
print(list1)  # [123, 456, 123, 456, 123, 456]
num = list1.count(123)
print(num)  # 3

[123, 456, 123, 456, 123, 456]
3


list.index(x[, start[, end]]) 从列表中找出某个值第一个匹配项的索引位置

In [29]:
list1 = [123, 456] * 5
print(list1.index(123))  # 0
print(list1.index(123, 1))  # 2
print(list1.index(123, 3, 7))  # 4

0
2
4


list.reverse() 反向列表中元素

In [30]:
x = [123, 456, 789]
x.reverse()
print(x)  # [789, 456, 123]

[789, 456, 123]


##### list.sort(key=None, reverse=False) 对原列表进行排序。

key -- 主要是用来进行比较的元素，只有一个参数，具体的函数的参数就是取自于可迭代对象中，指定可迭代对象中的一个元素来进行排序。

reverse -- 排序规则，reverse = True 降序， reverse = False 升序（默认）。

该方法没有返回值，但是会对列表的对象进行排序。

In [31]:
x = [123, 456, 789, 213]
x.sort()
print(x)
# [123, 213, 456, 789]

x.sort(reverse=True)
print(x)
# [789, 456, 213, 123]


# 获取列表的第二个元素
def takeSecond(elem):
    return elem[1]


x = [(2, 2), (3, 4), (4, 1), (1, 3)]
x.sort(key=takeSecond)
print(x)
# [(4, 1), (2, 2), (1, 3), (3, 4)]

x.sort(key=lambda a: a[0])
print(x)
# [(1, 3), (2, 2), (3, 4), (4, 1)]

[123, 213, 456, 789]
[789, 456, 213, 123]
[(4, 1), (2, 2), (1, 3), (3, 4)]
[(1, 3), (2, 2), (3, 4), (4, 1)]


## 元组

Python 的元组与列表类似，不同之处在于tuple被创建后就不能对其进行修改，类似字符串。

创建元组可以用小括号 ()，也可以什么都不用，为了可读性，建议还是用 ()。
元组中只包含一个元素时，需要在元素后面添加逗号，否则括号会被当作运算符使用。

In [1]:
t1 = (1, 10.31, 'python')
t2 = 1, 10.31, 'python'
print(t1, type(t1))
# (1, 10.31, 'python') <class 'tuple'>

print(t2, type(t2))
# (1, 10.31, 'python') <class 'tuple'>

(1, 10.31, 'python') <class 'tuple'>
(1, 10.31, 'python') <class 'tuple'>


In [2]:
x = (1)
print(type(x))  # <class 'int'>
x = 2, 3, 4, 5
print(type(x))  # <class 'tuple'>
x = []
print(type(x))  # <class 'list'>
x = ()
print(type(x))  # <class 'tuple'>
x = (1,)
print(type(x))  # <class 'tuple'>

<class 'int'>
<class 'tuple'>
<class 'list'>
<class 'tuple'>
<class 'tuple'>


#### 更新和删除一个元组

In [5]:
t1 = (1, 2, 3, [4, 5, 6])
print(t1)  # (1, 2, 3, [4, 5, 6])

t1[3][0] = 9
print(t1)  # (1, 2, 3, [9, 5, 6])

(1, 2, 3, [4, 5, 6])
(1, 2, 3, [9, 5, 6])


In [4]:
t1[0] = 10
#不可修改

TypeError: 'tuple' object does not support item assignment

#### 元组相关的操作符

等号操作符：==

连接操作符 +

重复操作符 *

成员关系操作符 in、not in

In [6]:
t1 = (123, 456)
t2 = (456, 123)
t3 = (123, 456)

print(t1 == t2)  # False
print(t1 == t3)  # True

t4 = t1 + t2
print(t4)  # (123, 456, 456, 123)

t5 = t3 * 3
print(t5)  # (123, 456, 123, 456, 123, 456)

t3 *= 3
print(t3)  # (123, 456, 123, 456, 123, 456)

print(123 in t3)  # True
print(456 not in t3)  # False

False
True
(123, 456, 456, 123)
(123, 456, 123, 456, 123, 456)
(123, 456, 123, 456, 123, 456)
True
False


#### 内置方法

元组大小和内容都不可更改，因此只有 count 和 index 两种方法。

In [7]:
t = (1, 10.31, 'python')
print(t.count('python'))  # 1
print(t.index(10.31))  # 1

1
1


#### 解压元组

解压（unpack）一维元组（有几个元素左边括号定义几个变量）

In [8]:
t = (1, 10.31, 'python')
(a, b, c) = t
print(a, b, c)
# 1 10.31 python

1 10.31 python


In [12]:
t = (1, 10.31, ('OK', 'python'))
(a, b, (c, d)) = t
print(a, b, c, d)
# 1 10.31 OK python

a,b,(c,d) = t
print(a,b,c,d)

1 10.31 OK python
1 10.31 OK python


如果你只想要元组其中几个元素，用通配符「*」，英文叫 wildcard，在计算机语言中代表一个或多个元素。下例就是把多个元素丢给了 rest 变量。

In [14]:
t = 1, 2, 3, 4, 5
a, b, *rest, c = t
print(a, b, c)  # 1 2 5
print(rest)  # [3, 4]

t = 1, 2, 3, 4, 5
a, b, *_ = t
print(a, b)  # 1 2

1 2 5
[3, 4]
1 2


## 字符串

In [15]:
t1 = 'i love Python!'
print(t1, type(t1))
# i love Python! <class 'str'>

t2 = "I love Python!"
print(t2, type(t2))
# I love Python! <class 'str'>

print(5 + 8)  # 13
print('5' + '8')  # 58

i love Python! <class 'str'>
I love Python! <class 'str'>
13
58


|转义字符|描述|
|---|---|
|`\\`|反斜杠符号||
|`\'`|单引号|
|`\"`|双引号|
|`\n`|换行|
|`\t`|横向制表符(TAB)|
|`\r`|回车|


三引号允许一个字符串跨多行，字符串中可以包含换行符、制表符以及其他特殊字符。

In [1]:
para_str = """这是一个多行字符串的实例
多行字符串可以使用制表符
TAB ( \t )。
也可以使用换行符 [ \n ]。
"""
print(para_str)
# 这是一个多行字符串的实例
# 多行字符串可以使用制表符
# TAB (    )。
# 也可以使用换行符 [
#  ]。

para_str = '''这是一个多行字符串的实例
多行字符串可以使用制表符
TAB ( \t )。
也可以使用换行符 [ \n ]。
'''
print(para_str)
# 这是一个多行字符串的实例
# 多行字符串可以使用制表符
# TAB ( 	 )。
# 也可以使用换行符 [ 
#  ]。

这是一个多行字符串的实例
多行字符串可以使用制表符
TAB ( 	 )。
也可以使用换行符 [ 
 ]。

这是一个多行字符串的实例
多行字符串可以使用制表符
TAB ( 	 )。
也可以使用换行符 [ 
 ]。



字符串的切片与拼接

In [2]:
str1 = 'I Love LsgoGroup'
print(str1[:6])  # I Love
print(str1[5])  # e
print(str1[:6] + " 插入的字符串 " + str1[6:])  
# I Love 插入的字符串  LsgoGroup

s = 'Python'
print(s)  # Python
print(s[2:4])  # th
print(s[-5:-2])  # yth
print(s[2])  # t
print(s[-1])  # n

I Love
e
I Love 插入的字符串  LsgoGroup
Python
th
yth
t
n


### 字符串的常用内置方法

capitalize() 将字符串的第一个字符转换为大写。

lower() 转换字符串中所有大写字符为小写。

upper() 转换字符串中的小写字母为大写。

swapcase() 将字符串中大写转换为小写，小写转换为大写。

In [3]:
str2 = 'xiaoxie'
print(str2.capitalize())  # Xiaoxie

Xiaoxie


In [4]:
str2 = "DAXIExiaoxie"
print(str2.lower())  # daxiexiaoxie
print(str2.upper())  # DAXIEXIAOXIE
print(str2.swapcase())  # daxieXIAOXIE

daxiexiaoxie
DAXIEXIAOXIE
daxieXIAOXIE


count(str, beg= 0,end=len(string)) 返回str在 string 里面出现的次数，如果beg或者end指定则返回指定范围内str出现的次数。

In [5]:
str2 = "DAXIExiaoxie"
print(str2.count('xi'))  # 2

2


endswith(suffix, beg=0, end=len(string)) 检查字符串是否以指定子字符串 suffix 结束，如果是，返回 True，否则返回 False。

如果 beg 和 end 指定值，则在指定范围内检查。

startswith(substr, beg=0,end=len(string)) 检查字符串是否以指定子字符串 substr 开头，如果是，返回 True，否则返回 False。

如果 beg 和 end 指定值，则在指定范围内检查。

In [6]:
str2 = "DAXIExiaoxie"
print(str2.endswith('ie'))  # True
print(str2.endswith('xi'))  # False
print(str2.startswith('Da'))  # False
print(str2.startswith('DA'))  # True

True
False
False
True


find(str, beg=0, end=len(string)) 检测 str 是否包含在字符串中，

如果指定范围 beg 和 end，则检查是否包含在指定范围内，如果包含，返回开始的索引值，否则返回 -1。

rfind(str, beg=0,end=len(string)) 类似于 find() 函数，不过是从右边开始查找。

In [7]:
str2 = "DAXIExiaoxie"
print(str2.find('xi'))  # 5
print(str2.find('ix'))  # -1
print(str2.rfind('xi'))  # 9

5
-1
9


isnumeric() 如果字符串中只包含数字字符，则返回 True，否则返回 False。

In [8]:
str3 = '12345'
print(str3.isnumeric())  # True
str3 += 'a'
print(str3.isnumeric())  # False

True
False


ljust(width[, fillchar])返回一个原字符串左对齐，并使用fillchar（默认空格）填充至长度width的新字符串。

rjust(width[, fillchar])返回一个原字符串右对齐，并使用fillchar（默认空格）填充至长度width的新字符串。

In [10]:
str4 = '1101'
print(str4.ljust(8, '0'))  # 11010000
print(str4.rjust(8, '0'))  # 00001101

11010000
00001101


lstrip([chars]) 截掉字符串左边的空格或指定字符。

rstrip([chars]) 删除字符串末尾的空格或指定字符。

strip([chars]) 在字符串上执行lstrip()和rstrip()。

In [11]:
str5 = ' I Love LsgoGroup '
print(str5.lstrip())  # 'I Love LsgoGroup '
print(str5.lstrip().strip('I'))  # ' Love LsgoGroup '
print(str5.rstrip())  # ' I Love LsgoGroup'
print(str5.strip())  # 'I Love LsgoGroup'
print(str5.strip().strip('p'))  # 'I Love LsgoGrou'

I Love LsgoGroup 
 Love LsgoGroup 
 I Love LsgoGroup
I Love LsgoGroup
I Love LsgoGrou


partition(sub) 找到子字符串sub，把字符串分为一个三元组(pre_sub,sub,fol_sub)，如果字符串中不包含sub则返回('原字符串','','')。

rpartition(sub)类似于partition()方法，不过是从右边开始查找。


In [12]:
str5 = ' I Love LsgoGroup '
print(str5.strip().partition('o'))  # ('I L', 'o', 've LsgoGroup')
print(str5.strip().partition('m'))  # ('I Love LsgoGroup', '', '')
print(str5.strip().rpartition('o'))  # ('I Love LsgoGr', 'o', 'up')

('I L', 'o', 've LsgoGroup')
('I Love LsgoGroup', '', '')
('I Love LsgoGr', 'o', 'up')


replace(old, new [, max]) 把 将字符串中的old替换成new，如果max指定，则替换不超过max次。

In [14]:
str = 'lululemon'
print(str.replace('lu','nu',1))
print(str.replace('lu','nu',2))

nululemon
nunulemon


split(str="", num) 不带参数默认是以空格为分隔符切片字符串，如果num参数有设置，则仅分隔num个子字符串，返回切片后的子字符串拼接的列表。

In [15]:
str5 = ' I Love LsgoGroup '
print(str5.strip().split())  # ['I', 'Love', 'LsgoGroup']
print(str5.strip().split('o'))  # ['I L', 've Lsg', 'Gr', 'up']

['I', 'Love', 'LsgoGroup']
['I L', 've Lsg', 'Gr', 'up']


splitlines([keepends]) 按照行('\r', '\r\n', \n')分隔，返回一个包含各行作为元素的列表，

如果参数keepends为 False，不包含换行符，如果为 True，则保留换行符。

In [16]:
str6 = 'I \n Love \n LsgoGroup'
print(str6.splitlines())  # ['I ', ' Love ', ' LsgoGroup']
print(str6.splitlines(True))  # ['I \n', ' Love \n', ' LsgoGroup']

['I ', ' Love ', ' LsgoGroup']
['I \n', ' Love \n', ' LsgoGroup']


maketrans(intab, outtab) 创建字符映射的转换表，第一个参数是字符串，表示需要转换的字符，第二个参数也是字符串表示转换的目标。


translate(table, deletechars="") 根据参数table给出的表，转换字符串的字符，要过滤掉的字符放到deletechars参数中。

In [17]:
str7 = 'this is string example....wow!!!'
intab = 'aeiou'
outtab = '12345'
trantab = str7.maketrans(intab, outtab)
print(trantab)  # {97: 49, 111: 52, 117: 53, 101: 50, 105: 51}
print(str7.translate(trantab))  # th3s 3s str3ng 2x1mpl2....w4w!!!

{97: 49, 101: 50, 105: 51, 111: 52, 117: 53}
th3s 3s str3ng 2x1mpl2....w4w!!!


maketrans() 是字符串对象的一个方法，用于创建一个字符转换表。

该方法接受两个参数 intab 和 outtab，并返回一个字典，字典的键是 intab 中字符的 ASCII 码值，值是 outtab 中对应位置字符的 ASCII 码值。

在这个例子中，trantab 是一个字典，其内容为 {97: 49, 111: 52, 117: 53, 101: 50, 105: 51}，其中 97 是 a 的 ASCII 码值，49 是 1 的 ASCII 码值，以此类推。


#### 字符串格式化

In [18]:
str8 = "{0} Love {1}".format('I', 'Lsgogroup')  # 位置参数
print(str8)  # I Love Lsgogroup

str8 = "{a} Love {b}".format(a='I', b='Lsgogroup')  # 关键字参数
print(str8)  # I Love Lsgogroup

str8 = "{0} Love {b}".format('I', b='Lsgogroup')  # 位置参数要在关键字参数之前
print(str8)  # I Love Lsgogroup

str8 = '{0:.2f}{1}'.format(27.658, 'GB')  # 保留小数点后两位
print(str8)  # 27.66GB

I Love Lsgogroup
I Love Lsgogroup
I Love Lsgogroup
27.66GB


|符号|描述|
|---|---|
|%c|格式化字符及其ASCII码|
|%s|格式化字符串，用str()方法处理对象|
|%r|格式化字符串，用rper()方法处理对象|
|%d|格式化整数|
|%o|格式化无符号八进制数|
|%x|格式化无符号十六进制数|
|%X|格式化无符号十六进制数（大写）|
|%f|格式化浮点数字，可指定小数点后的精度|
|%e|用科学计数法格式化浮点数|
|%E|作用同%e，用科学计数法格式化浮点数|
|%g|根据值的大小决定使用%f或%e|
|%G|作用同%g，根据值的大小决定使用%f或%E|


In [19]:
print('%c' % 97)  # a
print('%c %c %c' % (97, 98, 99))  # a b c
print('%d + %d = %d' % (4, 5, 9))  # 4 + 5 = 9
print("我叫 %s 今年 %d 岁!" % ('小明', 10))  # 我叫 小明 今年 10 岁!
print('%o' % 10)  # 12
print('%x' % 10)  # a
print('%X' % 10)  # A
print('%f' % 27.658)  # 27.658000
print('%e' % 27.658)  # 2.765800e+01
print('%E' % 27.658)  # 2.765800E+01
print('%g' % 27.658)  # 27.658
text = "I am %d years old." % 22
print("I said: %s." % text)  # I said: I am 22 years old..
print("I said: %r." % text)  # I said: 'I am 22 years old.'

a
a b c
4 + 5 = 9
我叫 小明 今年 10 岁!
12
a
A
27.658000
2.765800e+01
2.765800E+01
27.658
I said: I am 22 years old..
I said: 'I am 22 years old.'.


|符号|功能|
|---|---|
|m.n|m是显示的最小总宽度，n是小数点后的位数（如果可用的话）|
|-|用作左对齐|
|+|在正数前面显示加号(+)|
|#|在八进制数前面显示零('0')，在十六进制前面显示'0x'或者'0X'(取决于用的是'x'还是'X')|
|0|显示的数字前面填充'0'而不是默认的空格|


In [20]:
print('%5.1f' % 27.658)  # ' 27.7'
print('%.2e' % 27.658)  # 2.77e+01
print('%10d' % 10)  # '        10'
print('%-10d' % 10)  # '10        '
print('%+d' % 10)  # +10
print('%#o' % 10)  # 0o12
print('%#x' % 108)  # 0x6c
print('%010d' % 5)  # 0000000005

 27.7
2.77e+01
        10
10        
+10
0o12
0x6c
0000000005


## 字典

字典是 Python 唯一的一个 映射类型，字符串、元组、列表属于序列类型

那么如何快速判断一个数据类型 X 是不是可变类型的呢？两种方法：

麻烦方法：用 id(X) 函数，对 X 进行某种操作，比较操作前后的 id，如果不一样，则 X 不可变，如果一样，则 X 可变。、

便捷方法：用 hash(X)，只要不报错，证明 X 可被哈希，即不可变，反过来不可被哈希，即可变。

In [21]:
i = 1
print(id(i))  # 140732167000896
i = i + 2
print(id(i))  # 140732167000960

l = [1, 2]
print(id(l))  # 4300825160
l.append('Python')
print(id(l))  # 4300825160

4309982992
4309983056
4363112704
4363112704


In [22]:
print(hash('Name'))  # 7047218704141848153

print(hash((1, 2, 'Python')))  # 1704535747474881831


-3154707662180609446
-4407913120934321209


In [23]:
print(hash([1, 2, 'Python']))
# TypeError: unhashable type: 'list'

TypeError: unhashable type: 'list'

#### 创建和访问字典

In [24]:
brand = ['李宁', '耐克', '阿迪达斯']
slogan = ['一切皆有可能', 'Just do it', 'Impossible is nothing']
print('耐克的口号是:', slogan[brand.index('耐克')])  
# 耐克的口号是: Just do it

dic = {'李宁': '一切皆有可能', '耐克': 'Just do it', '阿迪达斯': 'Impossible is nothing'}
print('耐克的口号是:', dic['耐克'])  
# 耐克的口号是: Just do it

耐克的口号是: Just do it
耐克的口号是: Just do it


In [26]:
dic1 = {1: 'one', 2: 'two', 3: 'three'}
print(dic1)  # {1: 'one', 2: 'two', 3: 'three'}
print(dic1[1])  # one


{1: 'one', 2: 'two', 3: 'three'}
one


In [27]:
print(dic1[4])  # KeyError: 4

KeyError: 4

通过构造函数dict来创建字典。

dict() 创建一个空的字典。

【例子】通过key直接把数据放入字典中，但一个key只能对应一个value，多次对一个key放入 value，后面的值会把前面的值冲掉。

In [28]:
dic = dict()
dic['a'] = 1
dic['b'] = 2
dic['c'] = 3

print(dic)
# {'a': 1, 'b': 2, 'c': 3}

dic['a'] = 11
print(dic)
# {'a': 11, 'b': 2, 'c': 3}

dic['d'] = 4
print(dic)
# {'a': 11, 'b': 2, 'c': 3, 'd': 4}

{'a': 1, 'b': 2, 'c': 3}
{'a': 11, 'b': 2, 'c': 3}
{'a': 11, 'b': 2, 'c': 3, 'd': 4}


dict(mapping) new dictionary initialized from a mapping object's (key, value) pairs


In [29]:
dic1 = dict([('apple', 4139), ('peach', 4127), ('cherry', 4098)])
print(dic1)  # {'cherry': 4098, 'apple': 4139, 'peach': 4127}

dic2 = dict((('apple', 4139), ('peach', 4127), ('cherry', 4098)))
print(dic2)  # {'peach': 4127, 'cherry': 4098, 'apple': 4139}

{'apple': 4139, 'peach': 4127, 'cherry': 4098}
{'apple': 4139, 'peach': 4127, 'cherry': 4098}


dict(**kwargs) -> new dictionary initialized with the name=value pairs in the keyword argument list. For example: dict(one=1, two=2)

【例子】这种情况下，键只能为字符串类型，并且创建的时候字符串不能加引号，加上就会直接报语法错误。

In [31]:
dic = dict(name='Tom', age=10)
print(dic)  # {'name': 'Tom', 'age': 10}
print(type(dic))  # <class 'dict'>

{'name': 'Tom', 'age': 10}
<class 'dict'>


In [32]:
dic = dict('name'='Tom', 'age'=10)
print(dic)  # {'name': 'Tom', 'age': 10}
print(type(dic))  # <class 'dict'>

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (448229374.py, line 1)

### 字典的内置方法

dict.fromkeys(seq[, value]) 用于创建一个新字典，以序列 seq 中元素做字典的键，value 为字典所有键对应的初始值。

In [33]:
seq = ('name', 'age', 'sex')
dic1 = dict.fromkeys(seq)
print(dic1)
# {'name': None, 'age': None, 'sex': None}

dic2 = dict.fromkeys(seq, 10)
print(dic2)
# {'name': 10, 'age': 10, 'sex': 10}

dic3 = dict.fromkeys(seq, ('小马', '8', '男'))
print(dic3)
# {'name': ('小马', '8', '男'), 'age': ('小马', '8', '男'), 'sex': ('小马', '8', '男')}

{'name': None, 'age': None, 'sex': None}
{'name': 10, 'age': 10, 'sex': 10}
{'name': ('小马', '8', '男'), 'age': ('小马', '8', '男'), 'sex': ('小马', '8', '男')}


dict.keys()返回一个可迭代对象，可以使用 list() 来转换为列表，列表为字典中的所有键。

In [34]:
dic = {'Name': 'lsgogroup', 'Age': 7}
print(dic.keys())  # dict_keys(['Name', 'Age'])
lst = list(dic.keys())  # 转换为列表
print(lst)  # ['Name', 'Age']

dict_keys(['Name', 'Age'])
['Name', 'Age']


dict.values()返回一个迭代器，可以使用 list() 来转换为列表，列表为字典中的所有值。

In [35]:
dic = {'Sex': 'female', 'Age': 7, 'Name': 'Zara'}
print(dic.values())
# dict_values(['female', 7, 'Zara'])

print(list(dic.values()))
# [7, 'female', 'Zara']

dict_values(['female', 7, 'Zara'])
['female', 7, 'Zara']


dict.items()以列表返回可遍历的 (键, 值) 元组数组。

In [36]:
dic = {'Name': 'Lsgogroup', 'Age': 7}
print(dic.items())
# dict_items([('Name', 'Lsgogroup'), ('Age', 7)])

print(tuple(dic.items()))
# (('Name', 'Lsgogroup'), ('Age', 7))

print(list(dic.items()))
# [('Name', 'Lsgogroup'), ('Age', 7)]

dict_items([('Name', 'Lsgogroup'), ('Age', 7)])
(('Name', 'Lsgogroup'), ('Age', 7))
[('Name', 'Lsgogroup'), ('Age', 7)]


dict.get(key, default=None) 返回指定键的值，如果值不在字典中返回默认值。

In [37]:
dic = {'Name': 'Lsgogroup', 'Age': 27}
print("Age 值为 : %s" % dic.get('Age'))  # Age 值为 : 27
print("Sex 值为 : %s" % dic.get('Sex', "NA"))  # Sex 值为 : NA
print(dic)  # {'Name': 'Lsgogroup', 'Age': 27}

Age 值为 : 27
Sex 值为 : NA
{'Name': 'Lsgogroup', 'Age': 27}


dict.setdefault(key, default=None)和get()方法 类似, 如果键不存在于字典中，将会添加键并将值设为默认值。

In [38]:
dic = {'Name': 'Lsgogroup', 'Age': 7}
print("Age 键的值为 : %s" % dic.setdefault('Age', None))  # Age 键的值为 : 7
print("Sex 键的值为 : %s" % dic.setdefault('Sex', None))  # Sex 键的值为 : None
print(dic)  
# {'Age': 7, 'Name': 'Lsgogroup', 'Sex': None}

Age 键的值为 : 7
Sex 键的值为 : None
{'Name': 'Lsgogroup', 'Age': 7, 'Sex': None}


dict.pop(key[,default])删除字典给定键 key 所对应的值，返回值为被删除的值。key 值必须给出。若key不存在，则返回 default 值。

del dict[key] 删除字典给定键 key 所对应的值。

dict.popitem()随机返回并删除字典中的一对键和值，如果字典已经为空，却调用了此方法，就报出KeyError异常。

In [39]:
dic1 = {1: "a", 2: [1, 2]}
print(dic1.pop(1), dic1)  # a {2: [1, 2]}

# 设置默认值，必须添加，否则报错
print(dic1.pop(3, "nokey"), dic1)  # nokey {2: [1, 2]}

del dic1[2]
print(dic1)  # {}

a {2: [1, 2]}
nokey {2: [1, 2]}
{}


In [40]:
dic1 = {1: "a", 2: [1, 2]}
print(dic1.popitem())  # {2: [1, 2]}
print(dic1)  # (1, 'a')

(2, [1, 2])
{1: 'a'}


dict.clear()用于删除字典内所有元素。

In [41]:
dic = {'Name': 'Zara', 'Age': 7}
print("字典长度 : %d" % len(dic))  # 字典长度 : 2
dic.clear()
print("字典删除后长度 : %d" % len(dic))  
# 字典删除后长度 : 0

字典长度 : 2
字典删除后长度 : 0


dict.copy()返回一个字典的浅复制。

In [42]:
dic1 = {'Name': 'Lsgogroup', 'Age': 7, 'Class': 'First'}
dic2 = dic1.copy()
print("dic2")  
{'Age': 7, 'Name': 'Lsgogroup', 'Class': 'First'}

dic2


{'Age': 7, 'Name': 'Lsgogroup', 'Class': 'First'}

In [44]:
dic1 = {'user': 'lsgogroup', 'num': [1, 2, 3]}

# 引用对象
dic2 = dic1  
# 浅拷贝父对象（一级目录），子对象（二级目录）不拷贝，还是引用
dic3 = dic1.copy()  

print(id(dic1))  # 148635574728
print(id(dic2))  # 148635574728
print(id(dic3))  # 148635574344

# 修改 data 数据
dic1['user'] = 'root'
dic1['num'].remove(1)

# 输出结果
print(dic1)  # {'user': 'root', 'num': [2, 3]}
print(dic2)  # {'user': 'root', 'num': [2, 3]}
print(dic3)  # {'user': 'lsgogrou', 'num': [2, 3]}

4363021888
4363021888
4363018112
{'user': 'root', 'num': [2, 3]}
{'user': 'root', 'num': [2, 3]}
{'user': 'lsgogroup', 'num': [2, 3]}


dict.update(dict2)把字典参数 dict2 的 key:value对 更新到字典 dict 里。


In [45]:
dic = {'Name': 'Lsgogroup', 'Age': 7}
dic2 = {'Sex': 'female', 'Age': 8}
dic.update(dic2)
print(dic)  
# {'Sex': 'female', 'Age': 8, 'Name': 'Lsgogroup'}

{'Name': 'Lsgogroup', 'Age': 8, 'Sex': 'female'}


## 集合
Python 中set与dict类似，也是一组key的集合，但不存储value。由于key不能重复，所以，在set中，没有重复的key。

In [46]:
num = {}
print(type(num))  # <class 'dict'>
num = {1, 2, 3, 4}
print(type(num))  # <class 'set'>

<class 'dict'>
<class 'set'>


先创建对象再加入元素。

在创建空集合的时候只能使用s = set()，因为s = {}创建的是空字典。

直接把一堆元素用花括号括起来{元素1, 元素2, ..., 元素n}。重复元素在set中会被自动被过滤。

使用set(value)工厂函数，把列表或元组转换成集合。


In [47]:
basket = set()
basket.add('apple')
basket.add('banana')
print(basket)  # {'banana', 'apple'}

{'banana', 'apple'}


In [48]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)  # {'banana', 'apple', 'pear', 'orange'}

{'pear', 'orange', 'banana', 'apple'}


In [49]:
a = set('abracadabra')
print(a)  
# {'r', 'b', 'd', 'c', 'a'}

b = set(("Google", "Lsgogroup", "Taobao", "Taobao"))
print(b)  
# {'Taobao', 'Lsgogroup', 'Google'}

c = set(["Google", "Lsgogroup", "Taobao", "Google"])
print(c)  
# {'Taobao', 'Lsgogroup', 'Google'}

{'d', 'c', 'b', 'a', 'r'}
{'Lsgogroup', 'Google', 'Taobao'}
{'Lsgogroup', 'Google', 'Taobao'}


`由于 set 存储的是无序集合，所以我们不可以为集合创建索引或执行切片(slice)操作，也没有键(keys)可用来获取集合中元素的值，但是可以判断一个元素是否在集合中。`

### 集合的内置方法
set.add(elmnt)用于给集合添加元素，如果添加的元素在集合中已存在，则不执行任何操作。

In [50]:
fruits = {"apple", "banana", "cherry"}
fruits.add("orange")
print(fruits)  
# {'orange', 'cherry', 'banana', 'apple'}

fruits.add("apple")
print(fruits)  
# {'orange', 'cherry', 'banana', 'apple'}

{'orange', 'banana', 'cherry', 'apple'}
{'orange', 'banana', 'cherry', 'apple'}


set.update(set)用于修改当前集合，可以添加新的元素或集合到当前集合中，如果添加的元素在集合中已存在，则该元素只会出现一次，重复的会忽略。

In [51]:
x = {"apple", "banana", "cherry"}
y = {"google", "baidu", "apple"}
x.update(y)
print(x)
# {'cherry', 'banana', 'apple', 'google', 'baidu'}

y.update(["lsgo", "dreamtech"])
print(y)
# {'lsgo', 'baidu', 'dreamtech', 'apple', 'google'}

{'google', 'banana', 'cherry', 'baidu', 'apple'}
{'google', 'lsgo', 'baidu', 'dreamtech', 'apple'}


set.remove(item) 用于移除集合中的指定元素。如果元素不存在，则会发生错误。

set.discard(value) 用于移除指定的集合元素。remove() 方法在移除一个不存在的元素时会发生错误，而 discard() 方法不会。

In [52]:
fruits = {"apple", "banana", "cherry"}
fruits.remove("banana")
print(fruits)  # {'apple', 'cherry'}

{'cherry', 'apple'}


In [53]:
fruits.remove("banana")

KeyError: 'banana'

In [54]:
fruits = {"apple", "banana", "cherry"}
fruits.discard("banana")
print(fruits)  # {'apple', 'cherry'}
fruits.discard("banana")


{'cherry', 'apple'}


set.pop() 用于随机移除一个元素。

In [55]:
fruits = {"apple", "banana", "cherry"}
x = fruits.pop()
print(fruits)  # {'cherry', 'apple'}
print(x)  # banana

{'cherry', 'apple'}
banana


由于 set 是无序和无重复元素的集合，所以两个或多个 set 可以做数学意义上的集合操作。

set1.intersection(set2) 返回两个集合的交集。

set1 & set2 返回两个集合的交集。

set1.intersection_update(set2) 交集，在原始的集合上移除不重叠的元素。

In [56]:
a = set('abracadabra')
b = set('alacazam')
print(a)  # {'r', 'a', 'c', 'b', 'd'}
print(b)  # {'c', 'a', 'l', 'm', 'z'}

c = a.intersection(b)
print(c)  # {'a', 'c'}
print(a & b)  # {'c', 'a'}
print(a)  # {'a', 'r', 'c', 'b', 'd'}

a.intersection_update(b)
print(a)  # {'a', 'c'}

{'d', 'c', 'b', 'a', 'r'}
{'z', 'm', 'c', 'a', 'l'}
{'c', 'a'}
{'c', 'a'}
{'d', 'c', 'b', 'a', 'r'}
{'c', 'a'}


set1.union(set1) 返回两个集合的并集。

set1 | set2 返回两个集合的并集。

In [57]:
a = set('abracadabra')
b = set('alacazam')
print(a)  # {'r', 'a', 'c', 'b', 'd'}
print(b)  # {'c', 'a', 'l', 'm', 'z'}

print(a | b)  
# {'l', 'd', 'm', 'b', 'a', 'r', 'z', 'c'}

c = a.union(b)
print(c)  
# {'c', 'a', 'd', 'm', 'r', 'b', 'z', 'l'}

{'d', 'c', 'b', 'a', 'r'}
{'z', 'm', 'c', 'a', 'l'}
{'d', 'z', 'm', 'c', 'b', 'a', 'l', 'r'}
{'d', 'z', 'm', 'c', 'b', 'a', 'l', 'r'}


set1.difference(set2) 返回集合的差集。

set1 - set2 返回集合的差集。

set1.difference_update(set2) 集合的差集，直接在原来的集合中移除元素，没有返回值。

In [58]:
a = set('abracadabra')
b = set('alacazam')
print(a)  # {'r', 'a', 'c', 'b', 'd'}
print(b)  # {'c', 'a', 'l', 'm', 'z'}

c = a.difference(b)
print(c)  # {'b', 'd', 'r'}
print(a - b)  # {'d', 'b', 'r'}

print(a)  # {'r', 'd', 'c', 'a', 'b'}
a.difference_update(b)
print(a)  # {'d', 'r', 'b'}

{'d', 'c', 'b', 'a', 'r'}
{'z', 'm', 'c', 'a', 'l'}
{'b', 'd', 'r'}
{'b', 'd', 'r'}
{'d', 'c', 'b', 'a', 'r'}
{'d', 'b', 'r'}


set1.symmetric_difference(set2)返回集合的异或。

set1 ^ set2 返回集合的异或。

set1.symmetric_difference_update(set2)移除当前集合中在另外一个指定集合相同的元素，并将另外一个指定集合中不同的元素插入到当前集合中。

In [59]:
a = set('abracadabra')
b = set('alacazam')
print(a)  # {'r', 'a', 'c', 'b', 'd'}
print(b)  # {'c', 'a', 'l', 'm', 'z'}

c = a.symmetric_difference(b)
print(c)  # {'m', 'r', 'l', 'b', 'z', 'd'}
print(a ^ b)  # {'m', 'r', 'l', 'b', 'z', 'd'}

print(a)  # {'r', 'd', 'c', 'a', 'b'}
a.symmetric_difference_update(b)
print(a)  # {'r', 'b', 'm', 'l', 'z', 'd'}

{'d', 'c', 'b', 'a', 'r'}
{'z', 'm', 'c', 'a', 'l'}
{'b', 'd', 'z', 'm', 'l', 'r'}
{'b', 'd', 'z', 'm', 'l', 'r'}
{'d', 'c', 'b', 'a', 'r'}
{'d', 'z', 'm', 'b', 'l', 'r'}


set1.issubset(set2)判断集合1是不是被其他集合2包含，如果是则返回 True，否则返回 False。

set1 <= set2 判断集合1是不是被其他集合2包含，如果是则返回 True，否则返回 False。

set1.issuperset(set2)用于判断集合1是不是包含其他集合2，如果是则返回 True，否则返回 False。

set1 >= set2 判断集合1是不是包含其他集合2，如果是则返回 True，否则返回 False。

In [60]:
x = {"a", "b", "c"}
y = {"f", "e", "d", "c", "b", "a"}
z = x.issubset(y)
print(z)  # True
print(x <= y)  # True

x = {"a", "b", "c"}
y = {"f", "e", "d", "c", "b"}
z = x.issubset(y)
print(z)  # False
print(x <= y)  # False

True
True
False
False


In [61]:
x = {"f", "e", "d", "c", "b", "a"}
y = {"a", "b", "c"}
z = x.issuperset(y)
print(z)  # True
print(x >= y)  # True

x = {"f", "e", "d", "c", "b"}
y = {"a", "b", "c"}
z = x.issuperset(y)
print(z)  # False
print(x >= y)  # False

True
True
False
False


set.isdisjoint(set) 用于判断两个集合是不是不相交，如果是返回 True，否则返回 False。

In [62]:
x = {"f", "e", "d", "c", "b"}
y = {"a", "b", "c"}
z = x.isdisjoint(y)
print(z)  # False

x = {"f", "e", "d", "m", "g"}
y = {"a", "b", "c"}
z = x.isdisjoint(y)
print(z)  # True

False
True


#### 不可变集合

Python 提供了不能改变元素的集合的实现版本，即不能增加或删除元素，类型名叫frozenset。需要注意的是frozenset仍然可以进行集合操作，只是不能用带有update的方法。

frozenset([iterable]) 返回一个冻结的集合，冻结后集合不能再添加或删除任何元素。

In [63]:
a = frozenset(range(10))  # 生成一个新的不可变集合
print(a)  
# frozenset({0, 1, 2, 3, 4, 5, 6, 7, 8, 9})

b = frozenset('lsgogroup')
print(b)  
# frozenset({'g', 's', 'p', 'r', 'u', 'o', 'l'})

frozenset({0, 1, 2, 3, 4, 5, 6, 7, 8, 9})
frozenset({'p', 'o', 'u', 's', 'l', 'g', 'r'})


## 序列

#### 针对序列的内置函数

list(sub) 把一个可迭代对象转换为列表。

tuple(sub) 把一个可迭代对象转换为元组。

str(obj) 把obj对象转换为字符串


In [64]:
a = list()
print(a)  # []

b = 'I Love LsgoGroup'
b = list(b)
print(b)  
# ['I', ' ', 'L', 'o', 'v', 'e', ' ', 'L', 's', 'g', 'o', 'G', 'r', 'o', 'u', 'p']

c = (1, 1, 2, 3, 5, 8)
c = list(c)
print(c)  # [1, 1, 2, 3, 5, 8]

[]
['I', ' ', 'L', 'o', 'v', 'e', ' ', 'L', 's', 'g', 'o', 'G', 'r', 'o', 'u', 'p']
[1, 1, 2, 3, 5, 8]


In [65]:
a = tuple()
print(a)  # ()

b = 'I Love LsgoGroup'
b = tuple(b)
print(b)  
# ('I', ' ', 'L', 'o', 'v', 'e', ' ', 'L', 's', 'g', 'o', 'G', 'r', 'o', 'u', 'p')

c = [1, 1, 2, 3, 5, 8]
c = tuple(c)
print(c)  # (1, 1, 2, 3, 5, 8)

()
('I', ' ', 'L', 'o', 'v', 'e', ' ', 'L', 's', 'g', 'o', 'G', 'r', 'o', 'u', 'p')
(1, 1, 2, 3, 5, 8)


In [73]:

a = [1,2,3]
b = __builtins__.str(a)  #str在之前被命名为某个变量，故用内置函数解决
print(type(b))

<class 'str'>


max(sub)返回序列或者参数集合中的最大值

min(sub)返回序列或参数集合中的最小值

In [74]:
print(max(1, 2, 3, 4, 5))  # 5
print(max([-8, 99, 3, 7, 83]))  # 99
print(max('IloveLsgoGroup'))  # v

5
99
v


In [75]:
print(min(1, 2, 3, 4, 5))  # 1
print(min([-8, 99, 3, 7, 83]))  # -8
print(min('IloveLsgoGroup'))  # G

1
-8
G


sum(iterable[, start=0]) 返回序列iterable与可选参数start的总和。

In [76]:
print(sum([1, 3, 5, 7, 9]))  # 25
print(sum([1, 3, 5, 7, 9], 10))  # 35
print(sum((1, 3, 5, 7, 9)))  # 25
print(sum((1, 3, 5, 7, 9), 20))  # 45

25
35
25
45


sorted(iterable, key=None, reverse=False) 对所有可迭代的对象进行排序操作。

iterable -- 可迭代对象。

key -- 主要是用来进行比较的元素，只有一个参数，具体的函数的参数就是取自于可迭代对象中，指定可迭代对象中的一个元素来进行排序。

reverse -- 排序规则，reverse = True 降序 ， reverse = False 升序（默认）。

返回重新排序的列表

In [77]:
x = [-8, 99, 3, 7, 83]
print(sorted(x))  # [-8, 3, 7, 83, 99]
print(sorted(x, reverse=True))  # [99, 83, 7, 3, -8]

t = ({"age": 20, "name": "a"}, {"age": 25, "name": "b"}, {"age": 10, "name": "c"})
x = sorted(t, key=lambda a: a["age"])
print(x)
# [{'age': 10, 'name': 'c'}, {'age': 20, 'name': 'a'}, {'age': 25, 'name': 'b'}]

[-8, 3, 7, 83, 99]
[99, 83, 7, 3, -8]
[{'age': 10, 'name': 'c'}, {'age': 20, 'name': 'a'}, {'age': 25, 'name': 'b'}]


reversed(seq) 函数返回一个反转的迭代器。

In [78]:
s = 'lsgogroup'
x = reversed(s)
print(type(x))  # <class 'reversed'>
print(x)  # <reversed object at 0x000002507E8EC2C8>
print(list(x))
# ['p', 'u', 'o', 'r', 'g', 'o', 'g', 's', 'l']

t = ('l', 's', 'g', 'o', 'g', 'r', 'o', 'u', 'p')
print(list(reversed(t)))
# ['p', 'u', 'o', 'r', 'g', 'o', 'g', 's', 'l']

r = range(5, 9)
print(list(reversed(r)))
# [8, 7, 6, 5]

x = [-8, 99, 3, 7, 83]
print(list(reversed(x)))
# [83, 7, 3, 99, -8]

<class 'reversed'>
['p', 'u', 'o', 'r', 'g', 'o', 'g', 's', 'l']
['p', 'u', 'o', 'r', 'g', 'o', 'g', 's', 'l']
[8, 7, 6, 5]
[83, 7, 3, 99, -8]


enumerate(sequence, [start=0])

用于将一个可遍历的数据对象(如列表、元组或字符串)组合为一个索引序列，同时列出数据和数据下标，一般用在 for 循环当中。

In [79]:
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
a = list(enumerate(seasons))
print(a)  
# [(0, 'Spring'), (1, 'Summer'), (2, 'Fall'), (3, 'Winter')]

b = list(enumerate(seasons, 1))
print(b)  
# [(1, 'Spring'), (2, 'Summer'), (3, 'Fall'), (4, 'Winter')]

for i, element in a:
    print('{0},{1}'.format(i, element))
# 0,Spring
# 1,Summer
# 2,Fall
# 3,Winter

[(0, 'Spring'), (1, 'Summer'), (2, 'Fall'), (3, 'Winter')]
[(1, 'Spring'), (2, 'Summer'), (3, 'Fall'), (4, 'Winter')]
0,Spring
1,Summer
2,Fall
3,Winter


zip(iter1 [,iter2 [...]])

用于将可迭代的对象作为参数，将对象中对应的元素打包成一个个元组，然后返回由这些元组组成的对象，这样做的好处是节约了不少的内存。

我们可以使用 list() 转换来输出列表。

如果各个迭代器的元素个数不一致，则返回列表长度与最短的对象相同，利用 * 号操作符，可以将元组解压为列表。

In [81]:
a = [1, 2, 3]
b = [4, 5, 6]
c = [4, 5, 6, 7, 8]

zipped = zip(a, b)
print(zipped)  # <zip object at 0x000000C5D89EDD88>

In [82]:
print(list(zipped))  # [(1, 4), (2, 5), (3, 6)]

[(1, 4), (2, 5), (3, 6)]


In [83]:
zipped = zip(a, c)
print(list(zipped))  # [(1, 4), (2, 5), (3, 6)]

[(1, 4), (2, 5), (3, 6)]


In [86]:
print(list(*zip(zipped)))

[]


In [87]:
a1, a2 = zip(*zip(a, b))
print(list(a1))  # [1, 2, 3]
print(list(a2))  # [4, 5, 6]

[1, 2, 3]
[4, 5, 6]
